# Generated by Django 3.2.17 on 2023-10-17 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylist',
            name='category',
            field=models.CharField(choices=[('hack', 'Hackathon'), ('work', 'Workshop'), ('design', 'Designathon'), ('sem', 'Seminar'), ('course', 'Courses')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='img',
            field=models.ImageField(default=None, upload_to='images/certificate'),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='level',
            field=models.CharField(choices=[('dis', 'District'), ('state', 'State'), ('col', 'College'), ('nat', 'National')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='activitylist',
            name='title',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electronics & Electrical Engineering'), ('CE', 'Civil Engineering'), ('MEC', 'Mechanical Engineering')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='reg',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('sem1', '1'), ('sem2', '2'), ('sem3', '3'), ('sem4', '4'), ('sem5', '5'), ('sem6', '6'), ('sem7', '7'), ('sem8', '8')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default=None, upload_to='images/avatar'),
        ),
    ]
