# Generated by Django 3.2.17 on 2023-10-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0004_auto_20231017_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electronics & Electrical Engineering'), ('CE', 'Civil Engineering'), ('MEC', 'Mechanical Engineering')], default=None, max_length=100)),
                ('sem', models.CharField(choices=[('sem1', '1'), ('sem2', '2'), ('sem3', '3'), ('sem4', '4'), ('sem5', '5'), ('sem6', '6'), ('sem7', '7'), ('sem8', '8')], default=None, max_length=5)),
                ('img', models.ImageField(default=None, upload_to='images/avatar')),
                ('batch', models.CharField(default=None, max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
